doug-martin/goqu

dataset_test.go, example_test.go, expressions.go
This allows goqu.I("col").As(goqu.I("other")) as well as the original goqu.I("col").As("other").
=> Allow aliases to IdentifierExpressions.

HISTORY.md, adapters/mysql/dataset_adapter_test.go, adapters/mysql/mysql_test.go, adapters/postgres/dataset_adapter_test.go, adapters/postgres/postgres_test.go, adapters/sqlite3/dataset_adapter_test.go, adapters/sqlite3/sqlite3_test.go, adapters_test.go, crud_exec.go, crud_exec_test.go, database_test.go, dataset_actions.go, dataset_actions_test.go, dataset_delete_test.go, dataset_insert_test.go, dataset_select.go, dataset_select_test.go, dataset_test.go, dataset_update_test.go, example_test.go, expressions.go
Update scan struct to parse the struct(s) and for the column names to be selected.
=> Update ScanStruct to parse structs for column names

adapters.go, adapters/mysql/dataset_adapter_test.go, adapters/mysql/mysql_test.go, adapters/postgres/dataset_adapter_test.go, adapters/postgres/postgres_test.go, adapters/sqlite3/dataset_adapter_test.go, adapters/sqlite3/sqlite3_test.go, adapters_test.go, crud_exec_test.go, database_test.go, dataset.go, dataset_actions_test.go, dataset_delete_test.go, dataset_insert_test.go, dataset_select_test.go, dataset_test.go, dataset_update_test.go, default_adapter.go
* Add support for accepting a slice of bytes for literal serialization
* Updated Goqu to use C2FO fork of Testify
=> Add literal bytes and update to c2fo testify

.travis.yml, HISTORY.md, crud_exec.go, crud_exec_test.go, dataset_insert_test.go, dataset_select_test.go, dataset_update_test.go
Added ability for ScanStruct to allow embedded pointers with tests (added test for ScanStructs since it was missing)
=> Fix issue #19 - Exec.ScanStruct does not allow embedded pointers

dataset_select_test.go, expressions.go
Hello!
I'm using goqu with MySQL dialect.
Problem description: If you make detailed Dataset (using Where) from base Dataset, already having some where clauses, sometimes added expressions could be presented in the base dataset or its derivatives.
For example:
```
baseDS := From(...).Select(...).Where(<some heavy expressions with subqueries etc.>)
// some conditional filtering
if doFilter {
baseDS = baseDS.Where(goqu.I("selected").Eq(1))
}
subDS1 := baseDS.Where(goqu.I("type").Eq("Type1"))
subDS2 := baseDS.Where(goqu.I("type").Eq("Type2")) //This may overwrite where clause for subDS1!
sql, _, err := subDS1.ToSql() // sql = SELECT ... ... WHERE ... ... AND "Type" = "Type2" ; should be "Type1"
...
```
This happens because of go append() behaviour - in expressionList.Append() it may return …
=> Bugfix for chained Where()

database_test.go, docker-compose.yml
The tests are currently failing due to a change to sqlmock. `*/?` needed to be escaped due to it being a regex.
Probably worth vendoring dependencies. If you are cool with that I can submit another PR.
=> Fixing broken tests due to changes to sqlmock

.travis.yml, adapters.go, adapters/mysql/dataset_adapter_test.go, adapters/mysql/mysql.go, dataset.go, dataset_delete.go, dataset_insert.go, dataset_select.go, dataset_test.go, dataset_update.go, default_adapter.go, example_test.go, expressions.go
Thanks for this great library; I've found it very useful and filled my needs for query generation. Just found one missing element that did exist in some of the other major query generators which is support for Common Table Expressions (CTEs), i.e. WITH clauses. This includes both WITH and WITH RECURSIVE versions and applies them to SELECT, UPDATE, DELETE and INSERT queries (although I am just using them in the SELECT context).
These are a useful way to build efficient queries by re-using commonly used subparts. They are supported in PostgreSQL (https://www.postgresql.org/docs/current/static/queries-with.html) and SQLite (https://sqlite.org/lang_with.html); and I noticed in the upcoming MySQL 8.0 currently in Beta (https://dev.mysql.com/doc/refman/8.0/en/with.html). I'm using PostgreSQL. …
=> Support for defining WITH clauses for Common Table Expressions (CTE)

dataset_insert.go, dataset_insert_test.go
I fixed an issue when builder does not add `on conflict` section into insert query with data set instead of slice of records. Test included.
=> insert select on conflict do update

adapters.go, dataset.go, dataset_select.go, dataset_select_test.go, default_adapter.go, expressions.go
This addresses #43.  It's a first stab, but hopefully close.
The public interface only exposes a .ForUpdate() method on the dataset for now, but under the hood it's built to support .ForNoKeyUpdate(), .ForShare(), and .ForKeyShare() as well.
=> Add support for "FOR UPDATE" and "SKIP LOCKED"

database.go, database_example_test.go, database_test.go
Add a new method `WithTx` for `Database`, allowing use like
```go
err := db.WithTx(func(tx *TxDatabase) error {
// do something with tx
return nil
})
```
=> Add new method WithTx for Database

sql_dialect.go, sql_dialect_test.go
bugfix: literalTime use t.UTC() , This behavior is different from the original sql.DB.
it change the origin location, so , time insert to database be changed and error
=> bugfix: literalTime use t.UTC() ,  This behavior is different from the original sql.DB

HISTORY.md, docs/inserting.md, docs/updating.md, exec/scanner_test.go, exp/exp.go, exp/insert.go, exp/insert_test.go, exp/record.go, exp/update.go, exp/update_test.go, insert_dataset_example_test.go, internal/util/reflect.go, internal/util/reflect_test.go, issues_test.go, update_dataset_example_test.go
* [FIX] Fix reflection errors related to nil pointers and unexported fields #118
* Unexported fields are ignored when creating a columnMap
* Nil embedded pointers will no longer cause a panic
* Fields on nil embedded pointers will be ignored when creating update or insert statements.
* [ADDED] You can now ingore embedded structs and their fields by using `db:"-"` tag on the embedded struct.
=> Fix for #118

HISTORY.md, dialect/mysql/mysql.go, dialect/sqlite3/sqlite3.go, docs/selecting.md, exp/select_clauses.go, exp/select_clauses_test.go, select_dataset.go, select_dataset_example_test.go, select_dataset_test.go, sql_dialect.go, sql_dialect_options.go, sql_dialect_test.go
* [Added] Support for `DISTINCT ON` clauses #119
=> Enhancement for #119

delete_dataset_test.go, insert_dataset.go, insert_dataset_test.go, select_dataset_test.go, truncate_dataset_test.go, update_dataset_test.go
bugfix: InsertDataset.WithDialect return old dataset, should be return new dataset
=> bugfix: InsertDataset.WithDialect return old dataset

.github/workflows/go.yml, HISTORY.md, database_test.go, dialect/mysql/mysql.go, dialect/mysql/mysql_test.go, dialect/postgres/postgres_test.go, dialect/sqlite3/sqlite3.go, docker-compose.yml, docs/selecting.md, exp/col.go, exp/exp.go, exp/func.go, exp/select_clauses.go, exp/select_clauses_test.go, exp/window.go, exp/window_func.go, exp/window_func_test.go, exp/window_test.go, expressions.go, expressions_example_test.go, expressions_test.go, select_dataset.go, select_dataset_example_test.go, select_dataset_test.go, sqlgen/expression_sql_generator.go, sqlgen/expression_sql_generator_test.go, sqlgen/select_sql_generator.go, sqlgen/select_sql_generator_test.go, sqlgen/sql_dialect_options.go, sqlgen/sql_dialect_options_test.go
* [ADDED] Window Function support #128
=> Window function support

delete_dataset.go, delete_dataset_test.go, docs/deleting.md, docs/inserting.md, docs/selecting.md, docs/updating.md, insert_dataset.go, insert_dataset_test.go, select_dataset.go, select_dataset_test.go, truncate_dataset.go, truncate_dataset_test.go, update_dataset.go, update_dataset_test.go
This addresses https://github.com/doug-martin/goqu/issues/150 by
adding SetError and Error methods to each dataset. This will allow
end-user query building (e.g. users of goqu) to be able to mark a
dataset as being in a failed state via SetError and not have to track
that separately.
It only sets the error if one has not already been set. It also sets it
on the underlying SQLBuilder so that it too will know about the error
and not try to proceed with any futher query building. As such, future
calls to ToSQL will return the error as well.
=> Add Error and SetError to all datasets.

delete_dataset.go, delete_dataset_test.go, exp/delete_clauses.go, exp/insert_clauses.go, exp/update_clauses.go, insert_dataset.go, insert_dataset_test.go, update_dataset.go, update_dataset_test.go
`InsertDataset.ReturnsColumns()` `UpdateDataset.ReturnsColumns()` `DeleteDataset.ReturnsColumns()` panic when `clauses.Returning()` return nil
=> Fix ReturnsColumns() nil pointer panic

HISTORY.md, delete_dataset.go, insert_dataset.go, issues_test.go, select_dataset.go, update_dataset.go
* Changed AppendSQL to set error if one is present
=> Fix for #183

HISTORY.md, dialect/sqlite3/sqlite3.go, dialect/sqlite3/sqlite3_dialect_test.go, dialect/sqlite3/sqlite3_test.go
* [FIXED] SQlite dialect escapes single quotes wrong, leads to SQL syntax error [#178](https://github.com/doug-martin/goqu/issues/178)
=> Fix for issue 178

HISTORY.md, issues_test.go, sqlgen/delete_sql_generator_test.go, sqlgen/expression_sql_generator.go, sqlgen/expression_sql_generator_test.go, sqlgen/insert_sql_generator_test.go, sqlgen/select_sql_generator_test.go, sqlgen/update_sql_generator_test.go
* Removed check for returning columns when using insert/update/delete in sub select
=> [FIXED] WITH clause without a RETURNING clause will panic [#177]

dialect/sqlite3/sqlite3.go, dialect/sqlite3/sqlite3_dialect_test.go, dialect/sqlite3/sqlite3_test.go, docs/dialect.md, sql_dialect.go
SQLite lacks support of SELECT FOR UPDATE: https://sqlite.org/lang_select.html
To enable cross-database queries building with that syntax and avoid additional conditions in application code, need to insert empty fragment for SQLite dialect
=> Fixes to sqlite dialect: do not add FOR UPDATE in SELECT, fix support for INSERT ON CONFLICT

exp/exp.go, exp/select_clauses_test.go
looks like it was not added accidentally in initial version :) anyway, it's convenient to have, I have at least one real use case where I need to know whether expression is prepared or not
=> add IsPrepared to SQLExpression interface

dialect/sqlserver/sqlserver.go, dialect/sqlserver/sqlserver_test.go, sqlgen/common_sql_generator.go, sqlgen/sql_dialect_options.go
Added one more dialect property to be consistent with current approach (but placeholder with format for LIMIT fragment looked better IMHO)
=> fix SQLServer dialect: support prepared statements with TOP, closes #225

database.go, database_test.go, dialect/sqlserver/sqlserver.go, dialect/sqlserver/sqlserver_test.go, sqlgen/expression_sql_generator.go, sqlgen/sql_dialect_options.go
my proposal for fixing #239, new side effect is that explicit error will be returned when trying to construct query with IS / IS NOT operator other than for NULL value as RHS
Also, seems like support of boolean data type is a common "problem", AFAIK Oracle also does not have support for boolean, so explicit specification of it on dialect level looks good.
second commit is about handling panics in WithTx. It is not very uncommon situation when panic occurs inside for example REST handler for some reason. In this case current implementation will end up with "stuck" transaction which could prevent another transactions from normal operation.
=> use valid 'IS' operator for sqlserver dialect, fixes #239

dialect/postgres/postgres_test.go, exp/exp.go, exp/func.go, exp/func_test.go, exp/window_func.go, exp/window_func_test.go
A detailed description of the issue can be found here: #250
=> implement Orderable interface for SQL Functions

delete_dataset_example_test.go, dialect/mysql/mysql.go, sqlgen/delete_sql_generator.go, sqlgen/sql_dialect_options.go
Example explains w/o and w. table hint, difference is obvious, and affects query efficiency dramatically
```sql
EXPLAIN DELETE FROM `t1` WHERE ((`t1`.`id` IN ((SELECT `id` FROM `t2` WHERE (`t2`.`p` LIKE '/a/b/%')))) AND (`t1`.`v1` IS NULL) AND (`t1`.`v2` = -1))
+----+--------------------+--------------+------------+-----------------+------------------+---------+---------+--------+--------+----------+-------------+
| id | select_type        | table        | partitions | type            | possible_keys    | key     | key_len | ref    | rows   | filtered | Extra       |
+----+--------------------+--------------+------------+-----------------+------------------+---------+---------+--------+--------+----------+-------------+
| 1  | DELETE             | t1           | <null>     | ALL …
```
=> add support for table hint in multi-table MySQL DELETE queries

docs/database.md
Just a small syntax error in the docs on transactions.
=> Documentation typo - struct literals should have curly braces

exp/select_clauses.go, exp/select_clauses_test.go
I have encountered a bug, when having two separate `SelectDataset`s with some common part, they can override one anothers joins. Example datasets (build in order):
- common w/ joins: a, b, c
- derived1 (from common) w/ join: d
- derived2 (from common) w/ join: e 
Expected behavior would be to see:
- common joins: a, b, c
- derived1 joins: a, b, c, d
- derived2 joins: a, b, c, e
But the result actually is:
- common joins: a, b, c
- derived1 joins: a, b, c, e
- derived2 joins: a, b, c, e
Therefore `derived2` dataset overrides the joins of `derived1`. This can happen for all additional joins for common parts with number of joins < 2^n. This is consequence of [append(ret.joins, jc)](https://github.com/doug-martin/goqu/blob/master/exp/select_clauses.go#L190), which reallocates the data only …
=> Avoid mutation of join slice for separate datasets when `joins` slice capacity is not yet reached 

database_test.go, exec/query_executor.go, exec/query_executor_internal_test.go, exec/scanner.go, exec/scanner_internal_test.go, select_dataset_test.go
`ScanStructs`, `ScanVals` methods are added to `Scanner` interface.
Rationale is to allow reuse goqu very convenient struct tags in case when goqu is used as query builder only (i.e. queries built with goqu but executed via `sql` module API). In my case such approach allows to make some advanced query processing, like metrics collection or scanning results on-by-one - that's why goqu executor is not always suitable.
Also, I wanted to reuse code from `internal/utils` as much as possible
=> add ScanStructs, ScanVals to Scanner interface

database.go, goqu_example_test.go, sql_dialect.go, sqlgen/delete_sql_generator.go, sqlgen/expression_sql_generator.go, sqlgen/insert_sql_generator.go, sqlgen/select_sql_generator.go, sqlgen/truncate_sql_generator.go, sqlgen/update_sql_generator.go
now if I use `import` command at `github.com/doug-martin/goqu/v9/adapters/`
It doesn't work as below.
```
$ go get github.com/doug-martin/goqu/v9/adapters/postgres
go: downloading github.com/doug-martin/goqu v1.0.0
go: downloading github.com/doug-martin/goqu/v9 v9.13.0
go: downloading github.com/doug-martin/goqu v5.0.0+incompatible
go get: module github.com/doug-martin/goqu/v9@upgrade found (v9.13.0), but does not contain package github.com/doug-martin/goqu/v9/adapters/postgres
```
every implementation is fixed but some comments are still old links.
=> fix old import URL in comments

sqlgen/expression_sql_generator.go, sqlgen/expression_sql_generator_test.go
I've just copy-pasted https://github.com/doug-martin/goqu/pull/256 but added a simple test. Feel free to copypaste my test and merge original solution.
=> fix nil valuer #255

docs/selecting.md, goqu.go, insert_dataset_test.go, internal/util/column_map.go, internal/util/reflect.go, internal/util/reflect_test.go, select_dataset_test.go
Per https://github.com/doug-martin/goqu/issues/284
This adds a `SetIgnoreUntaggedFields` function which sets the behavior when
encountering struct fields that do not have a db tag. By default this is
false; if set to true any field without a db tag will not be targeted by
Select or Scan operations.
=> feat: allow untagged fields to be ignored

delete_dataset.go, delete_dataset_test.go, insert_dataset.go, insert_dataset_test.go, prepared.go, select_dataset.go, select_dataset_test.go, truncate_dataset.go, truncate_dataset_test.go, update_dataset.go, update_dataset_test.go
This switches the datasets' internal isPrepared bools into a custom type
that resolves back into a bool when passed into the SQL builder. This
could have also been a *bool but I wanted to avoid nil checks and
potential sources of confusion if e.g. a child dataset happened to
dereference and mutate the pointer's value.
Per #266
=> feat: add SetDefaultPrepared which controls query value interpolation

internal/util/column_map.go, issues_test.go
Fix for #290 
When creating the columnMap with multiple levels of embedded structs the append was mutating the original `fieldIndex` slice causing the fieldIndex for each column to be incorrect.
=> fix: field indexes getting overridden when appending

exp/case.go, exp/case_test.go, exp/exp.go, select_dataset_example_test.go
* Allow ordering by case expressions
=> feat: allow ordering by case expression

docs/inserting.md, docs/updating.md, exp/record.go, insert_dataset_example_test.go, internal/util/column_map.go, internal/util/reflect.go, internal/util/reflect_test.go, update_dataset_example_test.go
There are a couple of open issues which I think would be most elegantly resolved by the introduction of `omitempty` and/or `omitnil` struct tags: #174, #234. This PR introduces both tags.
This provides for much greater flexibility when handling partial inserts or updates. For example, we may handle a partial update as a struct of pointers, where null values are not to be updated.
```go
type PersonUpdate struct {
Name    *string `db:"name" goqu:"omitnil"`
Address *string `db:"address" goqu:"omitnil"`
}
address := "Test"
i := item{Address: &testString, Address2: &emptyString}
insertSQL, args, _ := goqu.Insert("items").Rows(i).ToSQL()
fmt.Println(insertSQL, args)
```
Output **before** this PR:
```
INSERT INTO "items" ("address", "name") VALUES ('Test', NULL) []
```
Output **after** this PR: …
=> feat: omitempty and omitnil struct tags

docs/updating.md, exp/update.go, update_dataset_example_test.go, update_dataset_test.go
Usually, a update looks like this:
```go
sql, _, _ := goqu.Update("items").Set(
goqu.Record{"name": "Test", "address": "111 Test Addr"},
).ToSQL()
```
Then you will get:
```sql
UPDATE "items" SET "address"='111 Test Addr',"name"='Test'
```
Note the fields are sorted. 
And now we can update like this:
```go
sql, _, _ := goqu.Update("items").Set([]exp.UpdateExpression{
goqu.C("name").Set("Test"),
goqu.C("address").Set("111 Test Addr"),
}).ToSQL()
```
Then you will get:
```sql
UPDATE "items" SET "name"='Test',"address"='111 Test Addr'
```
Note that the field "name"  is now in front of the field "address".
=> feat: allow []exp.UpdateExpression as Set values.
